export const stock = {
  colors: [
    "#FF0000",
    "#00FF00",
    "#0000FF",
    "#FFFF00",
    "#FF00FF",
    "#800080",
    "#008080",
    "#808000",
    "#800000",
    "#008000",
  ],
  sizes: [
    "XX-Small",
    "X-Small",
    "Small",
    "Medium",
    "Large",
    "X-Large",
    "XX-Large",
    "3X-Large",
    "4X-Large",
  ],
  dressStyles: ["Gym", "Casual", "Formal", "Party"],
  clothTypes: ["T-Shirt", "Hoodie", "Jacket", "Pants", "Shoes", "Socks"],
};
